### ISSUE TITLE
Took over 50 lines!

### ISSUE THREAD

**Issue by frasurebuilds** [chaseoes/PingChat#3]
XDDDDDDD Lol just minify it

**Comment by chaseoes** [comment]
Where do I say it's less than 50 lines?

**Comment by frasurebuilds** [comment]
Did you change it?
![screenshot_2016-05-16-15-42-12](https://cloud.githubusercontent.com/assets/9723817/15301651/ca972080-1b7c-11e6-87b9-27f877e2dfdf.png)

**Comment by chaseoes** [comment]
I don't know what you're talking about!
